spring:
  datasource:
    url: jdbc:h2:mem:testdb

  h2:
    console:
      enabled: true

  liquibase:
    enabled: true
    change-log: classpath:db.changelog/db.changelog-master.xml

  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: none
    show_sql: true

  jackson:
    deserialization:
      fail-on-unknown-properties: true

jwt:
  secret: "nsWpmZT0Xg7RDvniIWuSD34cWYFSXUja7BC8FJJxbh8"